/* 
 * bSDD API prototype
 *
 * API to access the buildingSMART Data Dictionary
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface ITextSearchListOpenApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Search the bSDD database using free text, get list of Classifications and/or Properties matching the text.
        /// </summary>
        /// <remarks>
        /// The details can be requested per Classification via the Classification API
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchText">The text to search for, minimum 3 characters (case and accent insensitive)</param>
        /// <param name="typeFilter">Type filter: must be \&quot;All\&quot;, \&quot;Classifications\&quot; or \&quot;Properties\&quot; (case sensitive) (optional)</param>
        /// <param name="domainNamespaceUris">List of domain to filter on (optional)</param>
        /// <returns>TextSearchResponseContractV5</returns>
        TextSearchResponseContractV5 ApiTextSearchListOpenV5Get (string searchText, string typeFilter = null, List<string> domainNamespaceUris = null);

        /// <summary>
        /// Search the bSDD database using free text, get list of Classifications and/or Properties matching the text.
        /// </summary>
        /// <remarks>
        /// The details can be requested per Classification via the Classification API
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchText">The text to search for, minimum 3 characters (case and accent insensitive)</param>
        /// <param name="typeFilter">Type filter: must be \&quot;All\&quot;, \&quot;Classifications\&quot; or \&quot;Properties\&quot; (case sensitive) (optional)</param>
        /// <param name="domainNamespaceUris">List of domain to filter on (optional)</param>
        /// <returns>ApiResponse of TextSearchResponseContractV5</returns>
        ApiResponse<TextSearchResponseContractV5> ApiTextSearchListOpenV5GetWithHttpInfo (string searchText, string typeFilter = null, List<string> domainNamespaceUris = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Search the bSDD database using free text, get list of Classifications and/or Properties matching the text.
        /// </summary>
        /// <remarks>
        /// The details can be requested per Classification via the Classification API
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchText">The text to search for, minimum 3 characters (case and accent insensitive)</param>
        /// <param name="typeFilter">Type filter: must be \&quot;All\&quot;, \&quot;Classifications\&quot; or \&quot;Properties\&quot; (case sensitive) (optional)</param>
        /// <param name="domainNamespaceUris">List of domain to filter on (optional)</param>
        /// <returns>Task of TextSearchResponseContractV5</returns>
        System.Threading.Tasks.Task<TextSearchResponseContractV5> ApiTextSearchListOpenV5GetAsync (string searchText, string typeFilter = null, List<string> domainNamespaceUris = null);

        /// <summary>
        /// Search the bSDD database using free text, get list of Classifications and/or Properties matching the text.
        /// </summary>
        /// <remarks>
        /// The details can be requested per Classification via the Classification API
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchText">The text to search for, minimum 3 characters (case and accent insensitive)</param>
        /// <param name="typeFilter">Type filter: must be \&quot;All\&quot;, \&quot;Classifications\&quot; or \&quot;Properties\&quot; (case sensitive) (optional)</param>
        /// <param name="domainNamespaceUris">List of domain to filter on (optional)</param>
        /// <returns>Task of ApiResponse (TextSearchResponseContractV5)</returns>
        System.Threading.Tasks.Task<ApiResponse<TextSearchResponseContractV5>> ApiTextSearchListOpenV5GetAsyncWithHttpInfo (string searchText, string typeFilter = null, List<string> domainNamespaceUris = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class TextSearchListOpenApi : ITextSearchListOpenApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TextSearchListOpenApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TextSearchListOpenApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TextSearchListOpenApi"/> class
        /// </summary>
        /// <returns></returns>
        public TextSearchListOpenApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TextSearchListOpenApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TextSearchListOpenApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Search the bSDD database using free text, get list of Classifications and/or Properties matching the text. The details can be requested per Classification via the Classification API
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchText">The text to search for, minimum 3 characters (case and accent insensitive)</param>
        /// <param name="typeFilter">Type filter: must be \&quot;All\&quot;, \&quot;Classifications\&quot; or \&quot;Properties\&quot; (case sensitive) (optional)</param>
        /// <param name="domainNamespaceUris">List of domain to filter on (optional)</param>
        /// <returns>TextSearchResponseContractV5</returns>
        public TextSearchResponseContractV5 ApiTextSearchListOpenV5Get (string searchText, string typeFilter = null, List<string> domainNamespaceUris = null)
        {
             ApiResponse<TextSearchResponseContractV5> localVarResponse = ApiTextSearchListOpenV5GetWithHttpInfo(searchText, typeFilter, domainNamespaceUris);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Search the bSDD database using free text, get list of Classifications and/or Properties matching the text. The details can be requested per Classification via the Classification API
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchText">The text to search for, minimum 3 characters (case and accent insensitive)</param>
        /// <param name="typeFilter">Type filter: must be \&quot;All\&quot;, \&quot;Classifications\&quot; or \&quot;Properties\&quot; (case sensitive) (optional)</param>
        /// <param name="domainNamespaceUris">List of domain to filter on (optional)</param>
        /// <returns>ApiResponse of TextSearchResponseContractV5</returns>
        public ApiResponse< TextSearchResponseContractV5 > ApiTextSearchListOpenV5GetWithHttpInfo (string searchText, string typeFilter = null, List<string> domainNamespaceUris = null)
        {
            // verify the required parameter 'searchText' is set
            if (searchText == null)
                throw new ApiException(400, "Missing required parameter 'searchText' when calling TextSearchListOpenApi->ApiTextSearchListOpenV5Get");

            var localVarPath = "/api/TextSearchListOpen/v5";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (searchText != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "SearchText", searchText)); // query parameter
            if (typeFilter != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "TypeFilter", typeFilter)); // query parameter
            if (domainNamespaceUris != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "DomainNamespaceUris", domainNamespaceUris)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiTextSearchListOpenV5Get", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TextSearchResponseContractV5>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TextSearchResponseContractV5) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TextSearchResponseContractV5)));
        }

        /// <summary>
        /// Search the bSDD database using free text, get list of Classifications and/or Properties matching the text. The details can be requested per Classification via the Classification API
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchText">The text to search for, minimum 3 characters (case and accent insensitive)</param>
        /// <param name="typeFilter">Type filter: must be \&quot;All\&quot;, \&quot;Classifications\&quot; or \&quot;Properties\&quot; (case sensitive) (optional)</param>
        /// <param name="domainNamespaceUris">List of domain to filter on (optional)</param>
        /// <returns>Task of TextSearchResponseContractV5</returns>
        public async System.Threading.Tasks.Task<TextSearchResponseContractV5> ApiTextSearchListOpenV5GetAsync (string searchText, string typeFilter = null, List<string> domainNamespaceUris = null)
        {
             ApiResponse<TextSearchResponseContractV5> localVarResponse = await ApiTextSearchListOpenV5GetAsyncWithHttpInfo(searchText, typeFilter, domainNamespaceUris);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Search the bSDD database using free text, get list of Classifications and/or Properties matching the text. The details can be requested per Classification via the Classification API
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchText">The text to search for, minimum 3 characters (case and accent insensitive)</param>
        /// <param name="typeFilter">Type filter: must be \&quot;All\&quot;, \&quot;Classifications\&quot; or \&quot;Properties\&quot; (case sensitive) (optional)</param>
        /// <param name="domainNamespaceUris">List of domain to filter on (optional)</param>
        /// <returns>Task of ApiResponse (TextSearchResponseContractV5)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TextSearchResponseContractV5>> ApiTextSearchListOpenV5GetAsyncWithHttpInfo (string searchText, string typeFilter = null, List<string> domainNamespaceUris = null)
        {
            // verify the required parameter 'searchText' is set
            if (searchText == null)
                throw new ApiException(400, "Missing required parameter 'searchText' when calling TextSearchListOpenApi->ApiTextSearchListOpenV5Get");

            var localVarPath = "/api/TextSearchListOpen/v5";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (searchText != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "SearchText", searchText)); // query parameter
            if (typeFilter != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "TypeFilter", typeFilter)); // query parameter
            if (domainNamespaceUris != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "DomainNamespaceUris", domainNamespaceUris)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiTextSearchListOpenV5Get", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TextSearchResponseContractV5>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TextSearchResponseContractV5) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TextSearchResponseContractV5)));
        }

    }
}
